services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/tabaco
    ports:
      - "5173:5173"
  mysql:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: tabaco
        MYSQL_ROOT_PASSWORD: root
        TZ: Asia/Tokyo
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
volumes:
  db-store: