services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/tabaco
    ports:
      - "5173:5173"
  mysql:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: tabaco
        MYSQL_ROOT_PASSWORD: root
        TZ: Asia/Tokyo
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  prisma_studio:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/tabaco
    command: npx prisma studio
    ports:
      - "5555:5555"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
volumes:
  db-store: