services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/tabaco
  mysql:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: tabaco
        MYSQL_ROOT_PASSWORD: root
        TZ: Asia/Tokyo
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  prisma_studio:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/tabaco
    command: ["./docker/scripts/wait-for-it.sh", "mysql:3306", "--", "npx", "prisma", "studio"]
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/html:/usr/share/nginx/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
volumes:
  db-store: